name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch
#defaults:
#  run:
#    working-directory: DotnetTemplate.Web

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Hello world       # Name of step
      run: echo 'Hello world' # Command to run

    - name: Hello world
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'

    - name: Build the C#       # Name of step
      run: dotnet build        # Command to run
  
    - name: Build the TypeScript code 1.      # Name of step
      working-directory: DotnetTemplate.Web
      run:  npm install        # Command to run

    - name: Build the TypeScript code 2.      # Name of step
      working-directory: DotnetTemplate.Web
      run:  npm run build        # Command to run

    - name: Run the C# Tests   # Name of step
      run: dotnet test         # Command to run

    - name: run the TypeScript tests  # Name of step
      working-directory: DotnetTemplate.Web
      run: npm t               # Command to run
      
    - name: un linting on the TypeScript code   # Name of step
      working-directory: DotnetTemplate.Web
      run: npm run lint         # Command to run

#New for Module 8

    - name: Login to Docker Hub   # Name of step
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 

    - name: Build Docker   # Name of step
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnettemplate:module8 .   # Command to run
      #run: docker build -t mattfo/dotnettemplate:module8 .    # Command to run

    - name: Publish to Docker Hub   # Name of step
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dotnettemplate:module8dock         # Push to Docker Hub
